services:
  frontend:
    container_name: tag-frontend
    image: tag-frontend:latest

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env.dev

    environment:
      - VITE_HOST
      - VITE_PORT
      - VITE_ALLOWED_HOSTS

    volumes:
      - .:/app
      - /app/dev/node_modules
      # - /app/prod/node_modules

    networks:
      - dev_network

    command: npm run dev

    expose:
      - 8080

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-dev.rule=Host(`test.thenagrygamershow.com`)"
      - "traefik.http.routers.frontend-dev.entrypoints=websecure"
      - "traefik.http.routers.frontend-dev.tls.certresolver=devresolver"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=8080"
