services:
  frontend:
    container_name: tag-frontend-dev
    image: tag-frontend:latest

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    env_file:
      - .env.dev

    environment:
      - VITE_HOST
      - VITE_PORT
      - VITE_ALLOWED_HOSTS

    volumes:
      - .:/app
      - node_modules:/app/node_modules

    networks:
      - dev_network

    command: npm run dev

volumes:
  node_modules: