services:
  frontend:
    container_name: tag-frontend
    image: tag-frontend:latest

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "192.168.0.199:5173:5173"
    
    env_file:
      - .env.dev

    # environment:
    #   - VITE_HOST
    #   - VITE_PORT
    #   - VITE_ALLOWED_HOSTS

    volumes:
      - .:/app
      - /app/dev/node_modules
      # - /app/dev/dist

    networks:
      - dev_network

    command: npm run dev

networks:
  dev_network:
    driver: bridge
